filter:
    excluded_paths: [Tests/*]

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

build:
    environment:
        php: 7.1.12
    dependencies:
        before:
            - composer require phpunit/phpunit:^7.1 --dev
    tests:
        override:
        -
            command: vendor/bin/phpunit --coverage-php
            coverage:
                file: clover.xml
                format: php-clover
