services:
    WowApps\SlackBundle\Service\SlackMessageBuilder:
        public: false
        autowire: false
        arguments:
            - '%wowapps.slackbot.config%'
            - '@WowApps\SlackBundle\Service\SlackColor'

    WowApps\SlackBundle\Service\SlackProvider:
        public: false
        autowire: false
        arguments:
            - '%wowapps.slackbot.config%'

    WowApps\SlackBundle\Service\SlackColor:
        public: false
        autowire: false
        arguments:
            - '%wowapps.slackbot.config%'

    WowApps\SlackBundle\Command\WowappsSlackbotTestCommand:
        public: false
        autowire: false
        tags: ['console.command']

    WowApps\SlackBundle\Service\SlackTemplatingManager:
        public: false
        autowire: false
        arguments:
            - '%wowapps.slackbot.config%'

    WowApps\SlackBundle\Service\SlackBot:
        public: false
        autowire: true
        arguments:
            - '%wowapps.slackbot.config%'
            - '@WowApps\SlackBundle\Service\SlackMessageBuilder'
            - '@WowApps\SlackBundle\Service\SlackProvider'
            - '@WowApps\SlackBundle\Service\SlackTemplatingManager'

    wowapps.slackbot:
        alias: WowApps\SlackBundle\Service\SlackBot
        public: true
